version: '3'
services:
 db:
  image: mysql:5.7
  container_name: mysql-nodedbapp
  security_opt:
    - seccomp:unconfined
  ports:
   - "3215:3306"
  volumes:
   - "./.data/db:/var/lib/mysql"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: testnodeapp
    MYSQL_USER: adonay
    MYSQL_PASSWORD: 123456

 app:
  depends_on:
   - db
  image: nodecustom	
  links:
    - db
  ports:
   - "3000:3000"
  restart: always
  environment:
    MYSQL_HOST: db
    MYSQL_USER: adonay
    MYSQL_PASSWORD: 123456
    MYSQL_DB: testnodeapp